// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ArticleID string  `json:"article_id"`
	Title     string  `json:"title"`
	Content   string  `json:"content"`
	Status    bool    `json:"status"`
	Author    *Author `json:"author"`
}

type Author struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

type NewArticle struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Status   bool   `json:"status"`
	AuthorID string `json:"AuthorID"`
}

type NewAuthor struct {
	Name string `json:"name"`
}
